### ISSUE TITLE
Unable to install aitviewer-skel on Windows

### ISSUE THREAD

**Issue by markus-albis** [MarilynKeller/aitviewer-skel#2]
I try to install aitviewer-skel following your instructions, I get the following error:

ERROR: Could not find a version that satisfies the requirement nimblephysics==0.10.32 (from aitviewer) (from versions: none)
ERROR: No matching distribution found for nimblephysics==0.10.32

OS: Windows 11 on amd64
Python: 3.9

**Comment by hwy1992129** [comment]
According to [nimblephysics'document ](https://nimblephysics.org/docs/install.html#common-errors-and-how-to-fix-them), "We do not currently support Windows. Windows users are recommended to use the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)."

**Comment by markus-albis** [comment]
aitviewer is a set of tools to visualize and interact with sequences of 3D data with cross-platform support on Windows, Linux, and macOS. It would be nice if aitviewer-skel is also cross-platform.

**Comment by MarilynKeller** [comment]
As the error says, nimblephisics is not supported on windows. It is only used to visualize the BSM.osim model. If you are not using BSM , you can remove the nimblephysics line in setup.py ([here](https://github.com/MarilynKeller/aitviewer-skel/blob/b39d0f446664fde168162c158a869c5ab3e70827/setup.py#L30)) and try to install again. You will still be able to visualize markers and SKEL.

**Comment by qaz8788817** [comment]
Hi. I am trying to install aitviewer-skel on Windows 10.
When I type the command `pip install -e .`, it shows the error below:
`
Obtaining file:///C:/Users/csie/Desktop/SKEL/aitviewer-skel
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\csie\desktop\skel\skel_venv\scripts\python.exe' 'c:\users\csie\desktop\skel\skel_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\csie\AppData\Local\Temp\tmp4pds9ukn'
       cwd: C:\Users\csie\Desktop\SKEL\aitviewer-skel
  Complete output (17 lines):
  Traceback (most recent call last):
    File "c:\users\csie\desktop\skel\skel_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 280, in <module>
      main()
    File "c:\users\csie\desktop\skel\skel_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\csie\desktop\skel\skel_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 114, in get_requires_for_build_wheel     
      return hook(config_settings)
    File "C:\Users\csie\AppData\Local\Temp\pip-build-env-vxhlf0ik\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel']) 
    File "C:\Users\csie\AppData\Local\Temp\pip-build-env-vxhlf0ik\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires       
      self.run_setup()
    File "C:\Users\csie\AppData\Local\Temp\pip-build-env-vxhlf0ik\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\csie\AppData\Local\Temp\pip-build-env-vxhlf0ik\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 42, in <module>
 'c:\users\csie\desktop\skel\skel_venv\lib\site-packages\pip\_vendor\pep517\in_procemultibyte sequencess\_in_process.py' get_requires_for_build_wheel 'C:\Users\csie\AppData\Local\Temp\tmp4pds9ukn' Check the logs for full command output.                                  ed out with exit status 1: 'c:\users\csie\desktop\skel\skel_venv\scripts\python.exe' 'c:\users\csie\desktop\skel\skel
ERROR: Command errored out with exit status 1: 'c:\users\csie\desktop\skel\skel_venvp517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\ logs for full command output.\scripts\python.exe' 'c:\users\csie\desktop\skel\skel_venv\lib\site-packages\pip\_ve                                                                       kages\pip\_vendor\pep517\in_process\_in_procesndor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\csie\A\scripts\python.exe' 'c:\users\csie\desktop\skel\skel_venv\lib\site-pacppData\Local\Temp\tmp4pds9ukn' Check the logs for full command output.              \Users\csie\AppData\Local\Temp\tmp4pds9ukn' Check the logs for full com
WARNING: You are using pip version 21.1.1; however, version 24.0 is available.      
You should consider upgrading via the 'c:\users\csie\desktop\skel\skel_venv\scripts\python.exe -m pip install --upgrade pip' command.                                   python.exe -m pip install --upgrade pip' command.
(skel_venv) PS C:\Users\csie\Desktop\SKEL\aitviewer-skel> pip install -e .
Obtaining file:///C:/Users/csie/Desktop/SKEL/aitviewer-skel
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\csie\desktop\skel\skel_venv\scripts\python.exe' 'c:\users\csie\desktop\skel\skel_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\csie\AppData\Local\Temp\tmpi661_nml'     
       cwd: C:\Users\csie\Desktop\SKEL\aitviewer-skel
  Complete output (17 lines):
  Traceback (most recent call last):
    File "c:\users\csie\desktop\skel\skel_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 280, in <module>
      main()
    File "c:\users\csie\desktop\skel\skel_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\csie\desktop\skel\skel_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\csie\AppData\Local\Temp\pip-build-env-p2bqg7tl\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel        
      return self._get_build_requires(config_settings, requirements=['wheel'])      
    File "C:\Users\csie\AppData\Local\Temp\pip-build-env-p2bqg7tl\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\csie\AppData\Local\Temp\pip-build-env-p2bqg7tl\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\csie\AppData\Local\Temp\pip-build-env-p2bqg7tl\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 42, in <module>
  UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 815: illegal 
multibyte sequence
`
Is this because aitviewer only supports Linux?
Thanks.

**Comment by loreofblasius** [comment]
Installation without nimblephysics was successful. I think you can close the issue.

**Comment by MarilynKeller** [comment]
@qaz8788817 It seems like your error is not due to using windows as it works for loreofblasius .

`cp950` is a code page used traditionally by Chinese Windows systems, maybe changing your system language to one that supports  UTF-8 (like english) can help but no guarranty here.

 If you can't fix it I suggest you set up a Ubuntu Virtual Machine.

**Comment by ZuoCX1996** [comment]
When try install on windows, if see
[UnicodeDecodeError: 'gbk' codec can't decode byte 0xa7 in position 817: illegal multibyte sequence]

Just modify the setup.py:
long_description=open("README.md").read() -> long_description=open("README.md", encoding='utf-8').read(),
